crystal_space/crystal_space/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns
from allauth.socialaccount.providers.facebook.provider import FacebookProvider
from allauth.socialaccount.providers.google.provider import GoogleProvider

urlpatterns = default_urlpatterns(FacebookProvider)
urlpatterns += default_urlpatterns(GoogleProvider)

urlpatterns += [
    url(r'^', include('home.urls')),
    url(r'^music/', include('music.urls')),
    url(r'^user/', include('users.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crystal_space/home/urls.py
from django.conf.urls import url
from .views import *


app_name = 'home'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^contact/$', ContactView.as_view(), name='contact'),
    url(r'^privacy-policy/$', PrivacyPolicyView.as_view(), name='privacy_policy'),
    url(r'^terms-and-conditions/$', TermsAndConditionsView.as_view(), name='terms_conditions'),
    url(r'^home-slider/$', HomeSliderView.as_view(), name='home_slider'),
    url(r'^newsletter_signin/$', NewsletterSigninView.as_view(), name='newsletter_signin'),
]

crystal_space/music/urls.py
from django.conf.urls import url
from .views import *

app_name = 'music'

urlpatterns = [
    url(r'^albums/$', AlbumListView.as_view(), name='albums'),
    url(r'^albums/play/(?P<pk>[0-9]+)/$', AlbumDetailView.as_view(), name='album_detail'),
    url(r'^albums/add/$', AlbumCreateView.as_view(), name='album_create'),
    url(r'^albums/(?P<pk>[0-9]+)/$', AlbumUpdateView.as_view(), name='album_update'),
    url(r'^albums/(?P<pk>[0-9]+)/delete/$', AlbumDeleteView.as_view(), name='album_delete'),
    url(r'^songs/add/(?P<album_pk>[0-9]+)/$', SongCreateView.as_view(), name='song_create'),
    url(r'^songs/(?P<pk>[0-9]+)/$', SongUpdateView.as_view(), name='song_update'),
    url(r'^songs/(?P<pk>[0-9]+)/delete/$', SongDeleteView.as_view(), name='song_delete'),
]

crystal_space/users/urls.py
from django.conf.urls import url, include
from .views import *

app_name = 'users'

urlpatterns = [
    url(r'^login/', UserLoginView.as_view(), name='login'),
    url(r'^logout/', logout_user, name='logout'),
    url(r'^register/', UserRegisterView.as_view(), name='register'),
]

crystal_space/crystal_space/templates/_form.html
{% load form_tags %}
{% for field in form %}
    <div class="form-group">
        <labe for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field|addcss:'form-control' }}
        <span class="text-danger small">{{ field.errors }}</span>
    </div>
{% endfor %}

crystal_space/crystal_space/templates/_layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CrystalSpace.cloud - {% block site_title %}{% endblock %}</title>

    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}"/>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Great+Vibes|Playball|Satisfy" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Gabriela" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="{% static 'css/site.css' %}" rel="stylesheet" type="text/css">
    {% block view_css %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-inverse navbar-static-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand crystal-space-logo" href="{% url 'home:index' %}">CrystalSpace.cloud</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
            {% if user.is_authenticated %}
            <ul class="nav navbar-nav">
                <li class="{% block albums_active %}{% endblock %}"><a href="{% url 'music:albums' %}"><i class="glyphicon glyphicon-cd" aria-hidden="true"></i> Albums</a></li>
            </ul>
            {% endif %}            
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}              
                {% if user.is_superuser %}
                    <li><a href="{% url 'admin:index' %}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Admin panel</a></li>
                {% endif %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        <i class="glyphicon glyphicon-user" aria-hidden="true"></i> {{ user.get_full_name|default:user.username }} <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" style="padding: 0;">
                        <li>
                            <form class="form-inline" role="form" action="{% url 'users:logout' %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-default btn-block"><i class="glyphicon glyphicon-log-out" aria-hidden="true"></i> Logout</button>
                            </form>
                        </li>
                    </ul> 
                </li>
                {% else %}  
                <li><a href="{% url 'users:login' %}"><i class="glyphicon glyphicon-log-in" aria-hidden="true"></i> Login</a></li> 
                {% endif %}
            </ul>
            </div>
        </div>
    </nav>

    {% block content %}{% endblock %}

    <footer class="footer {% block footer_class_ext %}{% endblock %}">
        <div class="conteiner-fluid">
            <div class="row">
                <div class="col-lg-1">&nbsp;</div>
                
                <div class="col-lg-3">
                    <h2 class="crystal-space-logo">CrystalSpace.cloud</h2>
                    <ul class="footer-motto-list">
                        <li class="motto-list-item">Cloud</li>
                        <li class="motto-list-item">Music</li>
                        <li class="motto-list-item">Player</li>
                    </ul>
                    <p>&copy; 2016 <a href="mailto:mateusz.bryll@outlook.com">Mateusz Bryll</a>, All rights reserved</p>
                </div>

                <div class="col-lg-2 footer-section">
                    <h4>More —</h4>
                    <ul class="list">
                        <li><a href="{% url 'home:contact' %}">Contact</a></li>
                        <li><a href="{% url 'home:terms_conditions' %}">Terms & Conditions</a></li>
                        <li><a href="{% url 'home:privacy_policy' %}">Privacy Policy</a></li>
                    </ul>
                </div>

                <div class="col-lg-2 footer-section">
                    <h4>Follow Us</h4>
                    <ul>
                        <li><a href="http://www.facebook.com">Facebook</a></li>
                        <li><a href="http://www.twitter.com">Twitter</a></li>
                        <li><a href="http://www.instagram.com">Instagram</a></li>
                    </ul>
                </div>

                <div class="col-lg-3 footer-section">
                    <h4>Newsletter</h4>
                    <p>Sign up for newsletter and get emails of great music</p>
                    <p>
                        <form action="{% url 'home:newsletter_signin' %}" method="POST">
                            <div class="input-group">
                            {% csrf_token %}
                            <input name="email" type="text" class="form-control" placeholder="your.email@server.com">
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-envelope"></span></button>
                            </span>
                            </div>
                        </form>
                    </p>
                </div>

                <div class="col-lg-1">&nbsp;</div>
            </div>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% block view_js %}{% endblock %}
</body>
</html>