crystal_space/crystal_space/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns
from allauth.socialaccount.providers.facebook.provider import FacebookProvider
from allauth.socialaccount.providers.google.provider import GoogleProvider

urlpatterns = default_urlpatterns(FacebookProvider)
urlpatterns += default_urlpatterns(GoogleProvider)

urlpatterns += [
    url(r'^', include('home.urls')),
    url(r'^music/', include('music.urls')),
    url(r'^user/', include('users.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crystal_space/home/urls.py
from django.conf.urls import url
from .views import *


app_name = 'home'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^contact/$', ContactView.as_view(), name='contact'),
    url(r'^privacy-policy/$', PrivacyPolicyView.as_view(), name='privacy_policy'),
    url(r'^terms-and-conditions/$', TermsAndConditionsView.as_view(), name='terms_conditions'),
    url(r'^home-slider/$', HomeSliderView.as_view(), name='home_slider'),
    url(r'^newsletter_signin/$', NewsletterSigninView.as_view(), name='newsletter_signin'),
]

crystal_space/users/urls.py
from django.conf.urls import url, include
from .views import *

app_name = 'users'

urlpatterns = [
    url(r'^login/', UserLoginView.as_view(), name='login'),
    url(r'^logout/', logout_user, name='logout'),
    url(r'^register/', UserRegisterView.as_view(), name='register'),
]

crystal_space/users/models.py
from django.db import models

crystal_space/users/forms.py
from django.contrib.auth.models import User
from django import forms


class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

crystal_space/users/views.py
from django.shortcuts import render, redirect
from django.views.generic import View, ListView
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.decorators import login_required
from .forms import UserLoginForm


def logout_user(request):
        logout(request);
        return redirect('users:login')


class UserLoginView(View):
    form_class = UserLoginForm
    template_name = 'users/login_form.html'

    def get(self, request):
        if request.user.is_authenticated and not request.user.is_anonymous():
            return redirect('home:index')

        return render(request, self.template_name, {'form': self.form_class(None)})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('home:index')
            
            return render(request, self.template_name, {'form': form, 'error_message': 'Invalid username or password.'})

        return render(request, self.template_name, {'form': form})


class UserRegisterView(View):
    form_class = UserCreationForm
    template_name = 'users/register_form.html'

    def get(self, request):
        if request.user.is_authenticated and not request.user.is_anonymous():
            return redirect('home:index')

        return render(request, self.template_name, {'form': self.form_class(None)})
    
    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            return redirect('users:login')
        return render(request, self.template_name, {'form': form})

crystal_space/users/templates/users/login_form.html
{% extends '_layout.html' %}
{% block site_title %}Login{% endblock %}
{% block view_css %}
{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/users_management.css' %}">
{% endblock %}


{% block content %}
<div class="content-container">
    <div class="col-md-3">&nbsp;</div>
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="col-md-12"><h2 class="form-header">Sign in</h2></div>
            <div class="panel-body">
                <div class="col-md-5 border-right">
                    <a href="{% url 'users:register' %}" class="btn btn-default btn-lg btn-block">Register new account</a>
                    <h3 class="text-center">Social Sign In</h3>
                    <a href="{% url 'facebook_login' %}" class="btn btn-primary btn-lg btn-block social-button"><i class="fa fa-facebook-official" aria-hidden="true"></i> Sign in with <strong>Facebook</strong></a>
                    <a href="{% url 'google_login' %}" class="btn btn-danger btn-lg btn-block social-button"><i class="fa fa-google-plus" aria-hidden="true"></i> Sign in with <strong>Google</strong></a>
                </div>
                <div class="col-md-1">&nbsp;</div>
                <div class="col-md-5">
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include '_form.html' %}
                        {% if error_message %}
                            <div class="alert alert-danger form-group">{{ error_message }}</div>
                        {% endif %}
                        <div class="form-group">
                            <button type="submit" class="btn btn-default pull-right">Sign in</button>
                        </div>
                    </form>
                </div>
                <div class="col-md-1">&nbsp;</div>
            </div>
            <div class="panel-footer">
                For Privacy Policy <a href="{% url 'home:privacy_policy' %}">click here</a>.
            </div>
        </div>
    </div>
    <div class="col-md-3">&nbsp;</div>
</div>
{% endblock %}

crystal_space/users/templates/users/register_form.html
{% extends '_layout.html' %}
{% block site_title %}Register{% endblock %}
{% block view_css %}
{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/users_management.css' %}">
{% endblock %}

{% block content %}

<div class="content-container">
    <div class="col-md-3">&nbsp;</div>
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="col-md-12"><h2 class="form-header">Register new Account</h2></div>
            <div class="panel-body">
                <div class="col-md-1">&nbsp;</div>
                <div class="col-md-10">
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include '_form.html' %}
                        <div class="form-group">
                            <button type="submit" class="btn btn-default pull-right">Register</button>
                        </div>
                    </form>
                </div>
                <div class="col-md-1">&nbsp;</div>
            </div>
            <div class="panel-footer">
                Already have an account? <a href="{% url 'users:login' %}">Click here</a> to log in.
            </div>
        </div>
    </div>
    <div class="col-md-3">&nbsp;</div>
</div>

{% endblock %}