crystal_space/crystal_space/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns
from allauth.socialaccount.providers.facebook.provider import FacebookProvider
from allauth.socialaccount.providers.google.provider import GoogleProvider

urlpatterns = default_urlpatterns(FacebookProvider)
urlpatterns += default_urlpatterns(GoogleProvider)

urlpatterns += [
    url(r'^', include('home.urls')),
    url(r'^music/', include('music.urls')),
    url(r'^user/', include('users.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crystal_space/home/urls.py
from django.conf.urls import url
from .views import *


app_name = 'home'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^contact/$', ContactView.as_view(), name='contact'),
    url(r'^privacy-policy/$', PrivacyPolicyView.as_view(), name='privacy_policy'),
    url(r'^terms-and-conditions/$', TermsAndConditionsView.as_view(), name='terms_conditions'),
    url(r'^home-slider/$', HomeSliderView.as_view(), name='home_slider'),
    url(r'^newsletter_signin/$', NewsletterSigninView.as_view(), name='newsletter_signin'),
]

crystal_space/music/urls.py
from django.conf.urls import url
from .views import *

app_name = 'music'

urlpatterns = [
    url(r'^albums/$', AlbumListView.as_view(), name='albums'),
    url(r'^albums/play/(?P<pk>[0-9]+)/$', AlbumDetailView.as_view(), name='album_detail'),
    url(r'^albums/add/$', AlbumCreateView.as_view(), name='album_create'),
    url(r'^albums/(?P<pk>[0-9]+)/$', AlbumUpdateView.as_view(), name='album_update'),
    url(r'^albums/(?P<pk>[0-9]+)/delete/$', AlbumDeleteView.as_view(), name='album_delete'),
    url(r'^songs/add/(?P<album_pk>[0-9]+)/$', SongCreateView.as_view(), name='song_create'),
    url(r'^songs/(?P<pk>[0-9]+)/$', SongUpdateView.as_view(), name='song_update'),
    url(r'^songs/(?P<pk>[0-9]+)/delete/$', SongDeleteView.as_view(), name='song_delete'),
]

crystal_space/music/models.py
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.db import models


def content_file_name(instance, filename):
    return '/'.join(['user_files', instance.user.username + '_' + str(instance.user.pk), filename])


class Album(models.Model):
    user = models.ForeignKey(User, default=1)
    artist = models.CharField(max_length=25)
    album_title = models.CharField(max_length=25)
    album_logo = models.FileField(upload_to=content_file_name)

    def get_absolute_url(self):
        return reverse('music:album_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.album_title


class Song(models.Model):
    user = models.ForeignKey(User, default=1)
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    song_title = models.CharField(max_length=255)
    audio_file = models.FileField(upload_to=content_file_name)

    def get_absolute_url(self):
        return reverse('music:album_detail', kwargs={'pk': str(self.album.pk)})

    def __str__(self):
        return self.song_title

crystal_space/music/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.views.generic import View, DetailView, ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from .models import *


class AlbumListView(ListView):
    model = Album
    template_name = 'music/albums.html'
    context_object_name = 'album_list'

    def get_queryset(self):
        return Album.objects.filter(user=self.request.user).order_by('album_title')


class AlbumDetailView(DetailView):
    model = Album
    template_name = 'music/songs.html'
    context_object_name = 'album'


class AlbumCreateView(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'album_logo']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(AlbumCreateView, self).form_valid(form)


class AlbumUpdateView(UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'album_logo']


class AlbumDeleteView(DeleteView):
    model = Album
    success_url = reverse_lazy('music:albums')


class SongCreateView(CreateView):
    model = Song
    fields = ['song_title', 'audio_file']

    #def get_initial(self):
    #    return { 'album': Album.objects.get(pk=self.kwargs['album_pk']) }

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.album = Album.objects.get(pk=self.kwargs['album_pk'])
        return super(SongCreateView, self).form_valid(form)


class SongUpdateView(UpdateView):
    model = Song
    fields = ['song_title', 'audio_file']


class SongDeleteView(DeleteView):
    model = Song

    def get_success_url(self):
        song = Song.objects.get(pk=self.kwargs['pk'])
        return reverse_lazy('music:album_detail', kwargs={'pk': str(song.album.pk)})

crystal_space/music/templates/music/album_form.html
{% extends '_layout.html' %}
{% block site_title %}Albums{% endblock %}
{% block view_css %}
{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/users_management.css' %}">
{% endblock %}


{% block content %}
<div class="content-container">
    <div class="col-md-3">&nbsp;</div>
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="col-md-12"><h2 class="form-header">Fill album information</h2></div>
            <div class="panel-body">
                <div class="col-md-1">&nbsp;</div>
                <div class="col-md-10">
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include '_form.html' %}
                        <div class="form-group">
                            <button type="submit" class="btn btn-default pull-right">Ok</button>
                        </div>
                    </form>
                </div>
                <div class="col-md-1">&nbsp;</div>
            </div>
        </div>
    </div>
    <div class="col-md-3">&nbsp;</div>
</div>
{% endblock %}

crystal_space/music/templates/music/albums.html
{% extends '_layout.html' %}
{% block site_title %}Albums{% endblock %}

{% block view_css %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/music.css' %}">
{% endblock %}

{% block albums_active %}active{% endblock %}

{% block content %}

{% load render_partial %}
{% render_partial 'home:home_slider' %}

<div class="content-container">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="col-md-1">&nbsp;</div>
                <div class="col-md-10">
                    <h2>Your albums</h2>
                    <a href="{% url 'music:album_create' %}" class="btn btn-default btn-small pull-right" style="right: 0; top: 20px; position: absolute;">
                        <i class="fa fa-plus" aria-hidden="true"></i> Add Album
                    </a>
                    <hr>
                    <div class="row">
                        {% for album in album_list %}
                        <div class="col-md-3">
                            <a href="{% url 'music:album_update' album.id %}" class="btn btn-default btn-small pull-right" style="width: 37px;">
                                <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                            </a>
                            <form action="{% url 'music:album_delete' album.id %}" method="POST" style="height: 30px;">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ album.id }}"/>
                                <button type="submit" class="btn btn-default btn-small pull-right">
                                    <i class="fa fa-trash-o" aria-hidden="true"></i>
                                </button>
                            </form>
                            <a href="{% url 'music:album_detail' pk=album.id %}" class="thumbnail">
                                <div class="hover-play-icon">
                                    <i class="fa fa-play" aria-hidden="true"></i>
                                </div>
                                <img src="{{ album.album_logo.url }}" alt="{{ album.album_title }}">
                                <div class="caption">
                                    <h3>{{ album.album_title }}</h3>
                                    <small>by {{ album.artist }}</small>
                                </div>
                            </a>
                        </div>
                        {% empty %}
                        <h3 style="margin: 40px 0px; display: block; text-align: center;">Your albums collection is empty. Please add new album.</h3>
                        {% endfor %}

                    </div>
                </div>
            <div class="col-md-1">&nbsp;</div>
        </div>
    </div>
</div>

{% endblock %}

{% block footer_class_ext %}footer-fluid{% endblock %}

crystal_space/music/templates/music/song_form.html
{% extends '_layout.html' %}
{% block site_title %}Albums{% endblock %}
{% block view_css %}
{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/users_management.css' %}">
{% endblock %}


{% block content %}
<div class="content-container">
    <div class="col-md-3">&nbsp;</div>
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="col-md-12"><h2 class="form-header">Fill song information</h2></div>
            <div class="panel-body">
                <div class="col-md-1">&nbsp;</div>
                <div class="col-md-10">
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include '_form.html' %}
                        <div class="form-group">
                            <button type="submit" class="btn btn-default pull-right">Ok</button>
                        </div>
                    </form>
                </div>
                <div class="col-md-1">&nbsp;</div>
            </div>
        </div>
    </div>
    <div class="col-md-3">&nbsp;</div>
</div>
{% endblock %}

crystal_space/music/templates/music/songs.html
{% extends '_layout.html' %}
{% block site_title %}Albums{% endblock %}

{% block view_css %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/music.css' %}">
{% endblock %}

{% block albums_active %}active{% endblock %}

{% block content %}

{% load render_partial %}
{% render_partial 'home:home_slider' %}

<div class="content-container">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="col-md-1">&nbsp;</div>
                <div class="col-md-10">
                    <h2>{{ album.album_title }}</h2>
                    <a href="{% url 'music:song_create' album.pk %}" class="btn btn-default btn-small pull-right" style="right: 0; top: 20px; position: absolute;">
                        <i class="fa fa-plus" aria-hidden="true"></i> Add Song
                    </a>
                    <hr>
                    {% if album.song_set.count > 0 %}
                        <div class="player">
                            <img class="player-album-logo" src="{{  album.album_logo.url }}" alt="text" />
                            <div class="player-audio">
                                <h3 id="song-title" class="player-song-title">{{  album.song_set.first.song_title }}</h3>
                                <h4 id="song-info" class="player-song-info">{{  album.album_title }} by {{  album.artist }}</h4>
                                <img class="player-background" src="{% static 'images/player_background.jpg' %}" alt="">
                                <audio id="audio" src="{{ album.song_set.first.audio_file.url }}" controls></audio>
                            </div>
                        </div>
                    <hr>
                    <table class="table"> 
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Song title</th>
                                <th>Album</th>
                                <th>Artist</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody id="playlist">
                            {% for song in album.song_set.all %}
                            <tr data-player-track="{{ song.audio_file.url }}"
                                data-player-track-title="{{ song.song_title }}"
                                data-player-track-album="{{ song.album.album_title }}"
                                data-player-track-artist="{{ song.album.artist }}"
                                {% if forloop.first %}
                                class="active"
                                {% endif %}
                                >
                                <td>{{ forloop.counter }}</td>
                                <td>{{ song.song_title }}</td>
                                <td>{{ song.album.album_title }}</td>
                                <td>{{ song.album.artist }}</td>
                                <td>
                                    <a style="width: 34px; height: 34px;" class="btn btn-default" href="{% url 'music:song_update' song.pk %}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                                    <form style="display: inline-block; width: 34px; height: 34px;" action="{% url 'music:song_delete' song.pk %}" method="POST">
                                        {% csrf_token %}
                                        <input type="hidden" name="song_id" value="{{ song.id }}"/>
                                        <button type="submit" class="btn btn-default">
                                            <i class="fa fa-trash-o" aria-hidden="true"></i>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    {% else %}
                    <div class="player">
                        <img class="player-album-logo" src="{{  album.album_logo.url }}" alt="text" />
                        <h3 style="flex-grow: 2; align-self: center; text-align: center;">This album is empty.</h3>
                    </div>
                    {% endif %}
                </div>
            <div class="col-md-1">&nbsp;</div>
        </div>
    </div>
</div>

{% endblock %}

{% block view_js %}
{% load static %}
<script src="{% static 'js/player.js' %}"></script>
{% endblock %}

{% block footer_class_ext %}footer-fluid{% endblock %}